apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback
  template:
    metadata:
      labels:
        app: feedback
    spec:
      containers:
      - image: nemanjas23/feedback:0.1
        name: feedback
        imagePullPolicy: "Always"
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-feedback:5432/feedback
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: dbuser
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP

